module.exports = {
  AdNotExistError:                              'ad not exist',
  AlreadyActivatedError:                        'already activated',
  AppNotExistError:                             'app not exist',
  AppPlatformSettingsNotExistError:             'app platform settings not exist',
  AttachmentNotExistError:                      'attachment not exist',
  ClientNotExistError:                          'client not exist',
  CubePointAggregationFailedError:              'failed to aggregate cube point',
  CubePointNotExistError:                       'cube point not exist',
  DuplicateKeyError:                            'duplicate key',
  FailedToCreateAdClickError:                   'failed to create ad click',
  FailedToCreateAdError:                        'failed to create ad',
  FailedToCreateAppPlatformSettingsError:       'failed to create app platform settings',
  FailedToCreateAttachmentError:                'failed to create attachment',
  FailedToCreateDeviceError:                    'failed to create device, contact us',
  FailedToCreateDeviceDataBlobError:            'failed to create device data blob',
  FailedToCreateGenreError:                     'failed to create genre',
  FailedToCreateMPoiWifiRuleError:              'failed to create poi wifi rule',
  FailedToCreatePlanError:                      'failed to create plan',
  FailedToCreatePoiError:                       'failed to create poi',
  FailedToCreateScenarioError:                  'failed to create scenario',
  FailedToCreateSubscriptionError:              'failed to create subscription',
  FailedToCreateUserError:                      'failed to create user',
  FailedToDeleteFileError:                      'failed to delete file',
  FailedToDestroyAdError:                       'failed to destroy ad',
  FailedToDestroyAppPlatformSettingsError:      'failed to destroy app platform settings',
  FailedToDestroyAttachmentError:               'failed to destroy attachment',
  FailedToDestroyGenreError:                    'failed to destroy genre',
  FailedToDestroyMPoiWifiRuleError:             'failed to destroy poi wifi rule',
  FailedToDestroyPlanError:                     'failed to destroy plan',
  FailedToDestroyScenarioError:                 'failed to destroy scenario',
  FailedToDestroySubscriptionError:             'failed to destroy subscription',
  FailedToEnsureDeviceError:                    'rpc error, failed to ensure device',
  FailedToExportPoiError:                       'failed to export poi',
  FailedToFindAdError:                          'failed to find ad',
  FailedToFindAppError:                         'failed to get app, check if appKey is valid',
  FailedToFindAppPlatformSettingsError:         'failed to find app platform settings',
  FailedToFindAttachmentError:                  'failed to find attachment',
  FailedToFindCubePointError:                   'failed to find cube point',
  FailedToFindFileError:                        'failed to find file',
  FailedToFindGenreError:                       'failed to find genre',
  FailedToFindJobError:                         'failed to find job',
  FailedToFindPlanError:                        'failed to find plan',
  FailedToFindPoiPullRequestError:              'failed to find poi pull request, contact us',
  FailedToFindPoisError:                        'failed to find pois',
  FailedToFindRegionsError:                     'failed to find regions',
  FailedToFindResourceError:                    'failed to find specified resource',
  FailedToFindScenarioError:                    'failed to find scenario',
  FailedToFindSubscriptionError:                'failed to find subscription',
  FailedToFindUserBehaviorsError:               'failed to find user behaviors',
  FailedToFindUsersError:                       'failed to find users',
  FailedToGenerateTokenError:                   'failed to generate token, contact us',
  FailedToGetAppError:                          'rpc error, failed to Get App',
  FailedToGetDeviceError:                       'failed to get device, contact us',
  FailedToGetJobError:                          'failed to get job status',
  FailedToGetPoiError:                          'rpc error, failed to get poi',
  FailedToHashPasswordError:                    'failed to hash password',
  FailedToImportPoiError:                       'failed to import error',
  FailedToQueueDeviceDataCollectJobError:       'failed to queue device data collect job',
  FailedToQueuePoiExportJobError:               'failed to queue poi export job',
  FailedToQueuePoiImportJobError:               'failed to queue poi import job',
  FailedToQueuePoiRemoveJobError:               'failed to queue poi remove job',
  FailedToQueuePoiRevertJobError:               'failed to queue poi revert job',
  FailedToReadCertificateError:                 'failed to read certificate, please check the password is correct',
  FailedToReadFileError:                        'error when read file',
  FailedToSaveDeviceError:                      'failed to create/update device, contact us',
  FailedToSaveFileError:                        'failed to save file',
  FailedToSaveUserError:                        'failed to save user, please check if required field is correct',
  FailedToSendMailError:                        'failed to send mail',
  FailedToUpdateAdError:                        'failed to update ad',
  FailedToUpdateAdLastOperationError:           'failed to update ad last operation',
  FailedToUpdateAppError:                       'failed to update app',
  FailedToUpdateAppLastOperationError:          'failed to update app last operation',
  FailedToUpdateAppPlatformSettingsError:       'failed to update app platform settings',
  FailedToUpdateAttachmentError:                'failed to update attachment',
  FailedToUpdateDeviceError:                    'failed to update device, contact us',
  FailedToUpdateGenreError:                     'failed to update genre',
  FailedToUpdateMPoiWifiRuleError:              'failed to update poi wifi rule',
  FailedToUpdatePlanError:                      'failed to update plan',
  FailedToUpdatePoiError:                       'failed to update poi',
  FailedToUpdatePoiPullRequestError:            'failed to update poi pull request',
  FailedToUpdateScenarioError:                  'failed to update scenario',
  FailedToUpdateScenarioLastOperationError:     'failed to update scenario last operation',
  FailedToUpdateSubscriptionError:              'failed to update subscription',
  FailedToUploadDeviceDataError:                'failed to upload data',
  FailedToValidateEmailError:                   'failed to validate email',
  FileNotExistError:                            'file not exist',
  GenreNotExistError:                           'genre not exist',
  InternalError:                                'internal error, contact us',
  InvalidActivationCodeError:                   'invalid activation code',
  InvalidAdSignatureError:                      'invalid ad signature',
  InvalidAppKeyError:                           'invalid appKey',
  InvalidAppSecretError:                        'invalid appSecret',
  InvalidClientKeyError:                        'invalid clientKey',
  InvalidClientSecretError:                     'invalid clientSecret',
  InvalidLocationError:                         'invalid location',
  InvalidPasswordResetCodeError:                'invalid password reset code',
  InvalidTokenError:                            'invalid token',
  MPoiWifiRuleNotExistError:                    'poi wifi rule not exist',
  NotYourAppError:                              'app is not yours',
  PasswordNotMatchError:                        'password not match',
  PendingPoiPullRequestExistsError:             'pending poi pull request exists',
  PlanNotExistError:                            'plan not exist',
  PoiNotExistError:                             'poi not exist',
  PoiNotReadyError:                             'poi not ready',
  PoiPullRequestNotActiveError:                 'poi pull request not active',
  PoiPullRequestNotExistError:                  'poi pull request not exist',
  RequireAdClickError:                          'require ad click',
  RequireAdError:                               'require ad',
  RequireAdIdError:                             'require ad id',
  RequireAppBundleError:                        'require appBundle',
  RequireAppError:                              'require app',
  RequireAppIdError:                            'require app id',
  RequireAppKeyError:                           'require appKey',
  RequireAppPlatformSettingsIdError:            'require app platform settings id',
  RequireAppSecretError:                        'require appSecret',
  RequireAttachmentError:                       'require attachment',
  RequireAttachmentIdError:                     'require attachment id',
  RequireBeaconsOrWifisOrLocationError:         'require beacon or wifi or location',
  RequireBssidError:                            'require wifi bssid',
  RequireClientKeyError:                        'require clientKey',
  RequireClientSecretError:                     'require clientSecret',
  RequireDeviceDataBlobError:                   'require device data blob',
  RequireDataFileError:                         'require uploaded data file',
  RequireDeviceError:                           'require device',
  RequireDeviceUdidError:                       'require deviceUdid',
  RequireFileBucketError:                       'require file bucket',
  RequireFilePathError:                         'require file path',
  RequireGenreError:                            'require genre',
  RequireGenreIdError:                          'require genre id',
  RequireJobIdError:                            'require job id',
  RequireMPoiWifiRuleError:                     'require poi wifi rule',
  RequireMPoiWifiRuleIdError:                   'require poi wifi rule id',
  RequireOwnerError:                            'require owner',
  RequirePasswordError:                         'require password',
  RequirePlanError:                             'require plan',
  RequirePlanIdError:                           'require plan id',
  RequirePoiError:                              'require poi',
  RequirePoiIdError:                            'require poi id',
  RequirePoiIdOrUmmError:                       'require poi id or umm',
  RequirePoiPullRequestError:                   'require poi pull request info',
  RequirePoiPullRequestIdError:                 'require poi pull request id',
  RequirePoisError:                             'require pois',
  RequireScenarioError:                         'require scenario',
  RequireScenarioIdError:                       'require scenario id',
  RequireSsidError:                             'require wifi ssid',
  RequireSubscriptionError:                     'require subscription',
  RequireSubscriptionIdError:                   'require subscription id',
  RequireTokenError:                            'require token',
  RequireUmmError:                              'require beacon umm',
  RequireUsernameError:                         'require username',
  RequireUserOrCodeToResetPasswordError:        'require user or code to reset password',
  ScenarioNotExistError:                        'scenario not exist',
  SubscriptionNotExistError:                    'subscription not exist',
  Success:                                      'success',
  SystemBusyError:                              'system busy, retry later',
  TokenExpiredError:                            'token is expired',
  UserAlreadySignupError:                       'failed to signup, user already signup',
  UserNotExistError:                            'user not exist',
  WrongParameterError:                          'wrong parameter'
};
